/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProofreaderQueueRouteImport } from './routes/proofreader.queue'
import { Route as DashboardReviewerRouteImport } from './routes/dashboard.reviewer'
import { Route as DashboardProofreaderRouteImport } from './routes/dashboard.proofreader'
import { Route as DashboardEditorRouteImport } from './routes/dashboard.editor'
import { Route as DashboardDecision_reviewerRouteImport } from './routes/dashboard.decision_reviewer'
import { Route as DashboardAuthorRouteImport } from './routes/dashboard.author'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as ContractCompleteRouteImport } from './routes/contract.complete'
import { Route as ProofreaderProposalTicketRouteImport } from './routes/proofreader.proposal.$ticket'
import { Route as DashboardProposalTicketRouteImport } from './routes/dashboard.proposal.$ticket'
import { Route as DashboardProofreader_proposalTicketRouteImport } from './routes/dashboard.proofreader_proposal.$ticket'
import { Route as DashboardAuthor_proposalIdRouteImport } from './routes/dashboard.author_proposal.$id'
import { Route as DashboardReviewerSubmissionIdRouteImport } from './routes/dashboard.reviewer.submission.$id'
import { Route as DashboardEditorSubmissionIdRouteImport } from './routes/dashboard.editor.submission.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofreaderQueueRoute = ProofreaderQueueRouteImport.update({
  id: '/proofreader/queue',
  path: '/proofreader/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewerRoute = DashboardReviewerRouteImport.update({
  id: '/dashboard/reviewer',
  path: '/dashboard/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProofreaderRoute = DashboardProofreaderRouteImport.update({
  id: '/dashboard/proofreader',
  path: '/dashboard/proofreader',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditorRoute = DashboardEditorRouteImport.update({
  id: '/dashboard/editor',
  path: '/dashboard/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDecision_reviewerRoute =
  DashboardDecision_reviewerRouteImport.update({
    id: '/dashboard/decision_reviewer',
    path: '/dashboard/decision_reviewer',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAuthorRoute = DashboardAuthorRouteImport.update({
  id: '/dashboard/author',
  path: '/dashboard/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractCompleteRoute = ContractCompleteRouteImport.update({
  id: '/contract/complete',
  path: '/contract/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofreaderProposalTicketRoute =
  ProofreaderProposalTicketRouteImport.update({
    id: '/proofreader/proposal/$ticket',
    path: '/proofreader/proposal/$ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProposalTicketRoute = DashboardProposalTicketRouteImport.update({
  id: '/dashboard/proposal/$ticket',
  path: '/dashboard/proposal/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProofreader_proposalTicketRoute =
  DashboardProofreader_proposalTicketRouteImport.update({
    id: '/dashboard/proofreader_proposal/$ticket',
    path: '/dashboard/proofreader_proposal/$ticket',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAuthor_proposalIdRoute =
  DashboardAuthor_proposalIdRouteImport.update({
    id: '/dashboard/author_proposal/$id',
    path: '/dashboard/author_proposal/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardReviewerSubmissionIdRoute =
  DashboardReviewerSubmissionIdRouteImport.update({
    id: '/submission/$id',
    path: '/submission/$id',
    getParentRoute: () => DashboardReviewerRoute,
  } as any)
const DashboardEditorSubmissionIdRoute =
  DashboardEditorSubmissionIdRouteImport.update({
    id: '/submission/$id',
    path: '/submission/$id',
    getParentRoute: () => DashboardEditorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contract/complete': typeof ContractCompleteRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/decision_reviewer': typeof DashboardDecision_reviewerRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/proofreader': typeof DashboardProofreaderRoute
  '/dashboard/reviewer': typeof DashboardReviewerRouteWithChildren
  '/proofreader/queue': typeof ProofreaderQueueRoute
  '/dashboard/author_proposal/$id': typeof DashboardAuthor_proposalIdRoute
  '/dashboard/proofreader_proposal/$ticket': typeof DashboardProofreader_proposalTicketRoute
  '/dashboard/proposal/$ticket': typeof DashboardProposalTicketRoute
  '/proofreader/proposal/$ticket': typeof ProofreaderProposalTicketRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
  '/dashboard/reviewer/submission/$id': typeof DashboardReviewerSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contract/complete': typeof ContractCompleteRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/decision_reviewer': typeof DashboardDecision_reviewerRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/proofreader': typeof DashboardProofreaderRoute
  '/dashboard/reviewer': typeof DashboardReviewerRouteWithChildren
  '/proofreader/queue': typeof ProofreaderQueueRoute
  '/dashboard/author_proposal/$id': typeof DashboardAuthor_proposalIdRoute
  '/dashboard/proofreader_proposal/$ticket': typeof DashboardProofreader_proposalTicketRoute
  '/dashboard/proposal/$ticket': typeof DashboardProposalTicketRoute
  '/proofreader/proposal/$ticket': typeof ProofreaderProposalTicketRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
  '/dashboard/reviewer/submission/$id': typeof DashboardReviewerSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contract/complete': typeof ContractCompleteRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/decision_reviewer': typeof DashboardDecision_reviewerRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/proofreader': typeof DashboardProofreaderRoute
  '/dashboard/reviewer': typeof DashboardReviewerRouteWithChildren
  '/proofreader/queue': typeof ProofreaderQueueRoute
  '/dashboard/author_proposal/$id': typeof DashboardAuthor_proposalIdRoute
  '/dashboard/proofreader_proposal/$ticket': typeof DashboardProofreader_proposalTicketRoute
  '/dashboard/proposal/$ticket': typeof DashboardProposalTicketRoute
  '/proofreader/proposal/$ticket': typeof ProofreaderProposalTicketRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
  '/dashboard/reviewer/submission/$id': typeof DashboardReviewerSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contract/complete'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/decision_reviewer'
    | '/dashboard/editor'
    | '/dashboard/proofreader'
    | '/dashboard/reviewer'
    | '/proofreader/queue'
    | '/dashboard/author_proposal/$id'
    | '/dashboard/proofreader_proposal/$ticket'
    | '/dashboard/proposal/$ticket'
    | '/proofreader/proposal/$ticket'
    | '/dashboard/editor/submission/$id'
    | '/dashboard/reviewer/submission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contract/complete'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/decision_reviewer'
    | '/dashboard/editor'
    | '/dashboard/proofreader'
    | '/dashboard/reviewer'
    | '/proofreader/queue'
    | '/dashboard/author_proposal/$id'
    | '/dashboard/proofreader_proposal/$ticket'
    | '/dashboard/proposal/$ticket'
    | '/proofreader/proposal/$ticket'
    | '/dashboard/editor/submission/$id'
    | '/dashboard/reviewer/submission/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/contract/complete'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/decision_reviewer'
    | '/dashboard/editor'
    | '/dashboard/proofreader'
    | '/dashboard/reviewer'
    | '/proofreader/queue'
    | '/dashboard/author_proposal/$id'
    | '/dashboard/proofreader_proposal/$ticket'
    | '/dashboard/proposal/$ticket'
    | '/proofreader/proposal/$ticket'
    | '/dashboard/editor/submission/$id'
    | '/dashboard/reviewer/submission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ContractCompleteRoute: typeof ContractCompleteRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardAuthorRoute: typeof DashboardAuthorRoute
  DashboardDecision_reviewerRoute: typeof DashboardDecision_reviewerRoute
  DashboardEditorRoute: typeof DashboardEditorRouteWithChildren
  DashboardProofreaderRoute: typeof DashboardProofreaderRoute
  DashboardReviewerRoute: typeof DashboardReviewerRouteWithChildren
  ProofreaderQueueRoute: typeof ProofreaderQueueRoute
  DashboardAuthor_proposalIdRoute: typeof DashboardAuthor_proposalIdRoute
  DashboardProofreader_proposalTicketRoute: typeof DashboardProofreader_proposalTicketRoute
  DashboardProposalTicketRoute: typeof DashboardProposalTicketRoute
  ProofreaderProposalTicketRoute: typeof ProofreaderProposalTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofreader/queue': {
      id: '/proofreader/queue'
      path: '/proofreader/queue'
      fullPath: '/proofreader/queue'
      preLoaderRoute: typeof ProofreaderQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviewer': {
      id: '/dashboard/reviewer'
      path: '/dashboard/reviewer'
      fullPath: '/dashboard/reviewer'
      preLoaderRoute: typeof DashboardReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/proofreader': {
      id: '/dashboard/proofreader'
      path: '/dashboard/proofreader'
      fullPath: '/dashboard/proofreader'
      preLoaderRoute: typeof DashboardProofreaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editor': {
      id: '/dashboard/editor'
      path: '/dashboard/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof DashboardEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/decision_reviewer': {
      id: '/dashboard/decision_reviewer'
      path: '/dashboard/decision_reviewer'
      fullPath: '/dashboard/decision_reviewer'
      preLoaderRoute: typeof DashboardDecision_reviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/author': {
      id: '/dashboard/author'
      path: '/dashboard/author'
      fullPath: '/dashboard/author'
      preLoaderRoute: typeof DashboardAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/complete': {
      id: '/contract/complete'
      path: '/contract/complete'
      fullPath: '/contract/complete'
      preLoaderRoute: typeof ContractCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofreader/proposal/$ticket': {
      id: '/proofreader/proposal/$ticket'
      path: '/proofreader/proposal/$ticket'
      fullPath: '/proofreader/proposal/$ticket'
      preLoaderRoute: typeof ProofreaderProposalTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/proposal/$ticket': {
      id: '/dashboard/proposal/$ticket'
      path: '/dashboard/proposal/$ticket'
      fullPath: '/dashboard/proposal/$ticket'
      preLoaderRoute: typeof DashboardProposalTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/proofreader_proposal/$ticket': {
      id: '/dashboard/proofreader_proposal/$ticket'
      path: '/dashboard/proofreader_proposal/$ticket'
      fullPath: '/dashboard/proofreader_proposal/$ticket'
      preLoaderRoute: typeof DashboardProofreader_proposalTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/author_proposal/$id': {
      id: '/dashboard/author_proposal/$id'
      path: '/dashboard/author_proposal/$id'
      fullPath: '/dashboard/author_proposal/$id'
      preLoaderRoute: typeof DashboardAuthor_proposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviewer/submission/$id': {
      id: '/dashboard/reviewer/submission/$id'
      path: '/submission/$id'
      fullPath: '/dashboard/reviewer/submission/$id'
      preLoaderRoute: typeof DashboardReviewerSubmissionIdRouteImport
      parentRoute: typeof DashboardReviewerRoute
    }
    '/dashboard/editor/submission/$id': {
      id: '/dashboard/editor/submission/$id'
      path: '/submission/$id'
      fullPath: '/dashboard/editor/submission/$id'
      preLoaderRoute: typeof DashboardEditorSubmissionIdRouteImport
      parentRoute: typeof DashboardEditorRoute
    }
  }
}

interface DashboardEditorRouteChildren {
  DashboardEditorSubmissionIdRoute: typeof DashboardEditorSubmissionIdRoute
}

const DashboardEditorRouteChildren: DashboardEditorRouteChildren = {
  DashboardEditorSubmissionIdRoute: DashboardEditorSubmissionIdRoute,
}

const DashboardEditorRouteWithChildren = DashboardEditorRoute._addFileChildren(
  DashboardEditorRouteChildren,
)

interface DashboardReviewerRouteChildren {
  DashboardReviewerSubmissionIdRoute: typeof DashboardReviewerSubmissionIdRoute
}

const DashboardReviewerRouteChildren: DashboardReviewerRouteChildren = {
  DashboardReviewerSubmissionIdRoute: DashboardReviewerSubmissionIdRoute,
}

const DashboardReviewerRouteWithChildren =
  DashboardReviewerRoute._addFileChildren(DashboardReviewerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ContractCompleteRoute: ContractCompleteRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardAuthorRoute: DashboardAuthorRoute,
  DashboardDecision_reviewerRoute: DashboardDecision_reviewerRoute,
  DashboardEditorRoute: DashboardEditorRouteWithChildren,
  DashboardProofreaderRoute: DashboardProofreaderRoute,
  DashboardReviewerRoute: DashboardReviewerRouteWithChildren,
  ProofreaderQueueRoute: ProofreaderQueueRoute,
  DashboardAuthor_proposalIdRoute: DashboardAuthor_proposalIdRoute,
  DashboardProofreader_proposalTicketRoute:
    DashboardProofreader_proposalTicketRoute,
  DashboardProposalTicketRoute: DashboardProposalTicketRoute,
  ProofreaderProposalTicketRoute: ProofreaderProposalTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
